config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount ActionCable.server => '/cable'

  root 'home#index'
  resources :messages
  resources :home, only: [:index], path: '' do
    collection do
      get 'privacy'
      get 'terms_of_use'
      get 'clear_messages'
      get 'terms_of_use'
      get 'loader'
      post 'create_subscriber'
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users
  namespace :api do
    namespace :v1 do
      resources :rooms, only: [] do
        post :users, to: 'rooms#add_user'
        get :network, to: 'rooms#get_network'
      end

      resources :reports, only: %i[] do
        collection do
          post :user
          post :message
        end
      end

      resources :blacklist, controller: 'blacklists', only: %i[index create] do
      end

      resources :registrations, only: %i[create update] do
        collection do
          get 'check_login'
        end
      end

      resources :providers, only: %i[create]
      resources :networks, only: %i[index create] do
        collection do
          get 'list'
        end
      end
      resources :messages do
        member do
          get 'room/messages', to: 'messages#messages_from_room'
          get 'room/users', to: 'messages#users_from_room'
          get 'reply/messages', to: 'messages#replies_on_message'
        end
        collection do
          post 'lock'
          post 'unlock'
          post 'delete'
          post 'sms_sharing'
          post 'share'
          get 'legendary_list'
          get 'profile_messages'
          get 'nearby_profile_messages'
          get 'profile_communities'
          get 'block'
          post 'social_feed'
          post 'delete_for_all'
          post 'update_message_points'
          put 'update_message_avatar'
          get 'nearby'
          get 'nearby_search'
          post 'send_notifications', to: 'messages#send_notifications'
          get 'non_custom_lines', to: 'messages#get_non_custom_lines'
          post 'conversation_update'
          get 'map_feed'
        end
      end
      resources :networks_users, only: %i[index create]
      resources :members, only: [:create]
      resource :profiles, only: %i[destroy]
      resources :profiles, only: %i[show] do
        collection do
          get 'user_by_provider'
          post 'connect_social'
          post 'change_points_count'
          get 'disabled_hero'
          get 'social_net_status'
          patch 'accept_terms_of_use'
        end
      end
      resources :sessions, only: %i[create destroy] do
        collection do
          get 'check'
          post 'oauth_login'
          post 'verification'
        end
      end
      resources :user_likes, only: [:create]
      resources :user_followed, only: [:create]
      resources :legendary_likes, only: %i[create index]
      resources :invitations, only: [:create]
      resources :contacts, only: [:create]
      resources :crons do
        collection do
          get 'todays_event_notifications'
          get 'reset_weekly_somvos'
          get 'remove_inactive_somvo'
        end
      end
      get '/sms', to: 'invitations#sms'

    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @subscriber = Subscriber.new
  end

  def create_subscriber
=begin
    render plain: params[:subscriber].inspect
=end
    @subscriber = Subscriber.find_by(email: params[:subscriber][:email])
    if @subscriber.present?
      flash[:notice] = 'User already exist...'
      redirect_to root_path
    else
      @subscriber = Subscriber.new(subscriber_params)
      if @subscriber.save
        flash[:notice] = 'Successfully subscribed...'
        redirect_to root_path
      else
        flash[:notice] = 'Sorry something went wrong...'
        redirect_to root_path
      end
    end
  end

  def privacy; end
  def terms_of_use; end
  def loader; end

  def clear_messages
    @messages = Message.all
    @messages.each(&:destroy)
    Image.all.map(&:destroy)
    redirect_to root_path
  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:email, :description)
  end
end

app/views/home/index.html.erb
<% if flash[:notice].present? %>
  <p class="notice">
    <%= flash[:notice] %>
  </p>
<% end %>
<div class="modal fade" id="modal-contact">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <%= form_for @subscriber, url: create_subscriber_home_index_path,
            method: :post do |f| %>
            <%= f.email_field :email, required: true, placeholder: "Email",
            class: "field email"%>
            <%= f.text_field :description, placeholder: "Tell me more",
            class: "field description" %>
            <%= f.submit "Send", class: "submit" %>
          <% end %>
          <span>
            <a href="/privacy">Privacy policy</a>
            |
            <a href="/terms_of_use">Terms of Use</a>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="modal-download">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <a href="https://itunes.apple.com/us/app/netwrk/id1216109944&ls=1&mt=8"
            target="_blank"
            class="appstore-link"><%= image_tag 'download/appstore.svg' %></a>
          <a href='https://play.google.com/store/apps/details?id=com.netwrk.android&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1'
            target="_blank"
            class="playmarket-link">
            <img alt='Get it on Google Play' src='https://play.google.com/intl/en_us/badges/images/generic/en_badge_web_generic.png'/>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="row main-row">
  <a href="#" class="left top-link run_download">Download<br class="res-nl"> the app</a>
  <a href="#" class="run_contactModal right top-link">Contact us</a>

  <div class="col-lg-2 col-md-2 col-sm-1 col-xs-12 left col"></div>
  <div class="col-lg-8 col-md-8 col-sm-10 col-xs-12 center col">
    <div class="center-container">
      <p>The story of netwrk</p>
      <button type="button" name="stories"></button>
    </div>
    <div id="stories">
      <%= form_for @subscriber, url: create_subscriber_home_index_path,
        method: :post do |f| %>
        <%= f.email_field :email, required: true, placeholder: "Email to subscribe",
        class: "field email"%>
        <%= f.submit "SEND", class: "submit" %>
      <% end %>
      <div class="stories-list">
        <%= raw ApplicationSetting.instance.home_page %>
      </div>
    </div>
  </div>
  <div class="col-lg-2 col-md-2 col-sm-1 col-xs-12 right col"></div>
</div>

app/views/home/loader.html.erb
<div class="placeholder-loader">
  <%= image_tag 'logo.svg' %>
  <h3>Loading</h3>
</div>

app/views/home/privacy.html.erb
<div class="container policy">
  <h1>Privacy policy</h1>
<p><span style="font-weight: 400;">Netwrk is an open platform that promotes all social media that are connected to us, and that we believe are good for the world. Facebook is the first thing you see on our profile, and we hope that people will use it to connect and friend others that they become aware of through our platform. Linkedin, snapchat, and Twitter can all be connected to a person&rsquo;s profile in similar fashion. Your profile becomes a way for anyone to find you on all connected social media. These posts are able to be shared from your profile, and when clicked on, will go to the corresponding platform, therefore promoting your profile on it and also the platform itself. We&rsquo;re trying to be cool with everyone out there, giving you the best local experience possible!</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">The use of this data is specified below. Yes, it is natural that you will be sharing some information with us and that it will affect your privacy. So we want to be very clear about how we use the information we collect, who we share it with, and where it can go after it comes on our platform. To be brief, we use the information to provide the best local products and services out there that we continually improve. </span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Your casts cannot go outside an area unless it is deemed legendary. Hey, thats a good thing, but with it also comes the potential that it can be seen nationally by anyone outside that spot. Hanging something undercover is not possible to share or be sent outside where it was posted unless another person takes a picture of it. </span><span style="font-weight: 400;">It&rsquo;s also possible, as with any digital information, that someone might be able to access messages forensically or find them in a device&rsquo;s temporary storage. </span><span style="font-weight: 400;">So when it comes to sharing outside content or posting your own, you can be rest assured it will not be taken outside of these bounds. </span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">If you have any questions about this policy, feel free to contact us.</span></p>
<p><br /><br /></p>
<h2><strong>Full policy</strong></h2>
<p>&nbsp;</p>
<h2><strong>Information we collect</strong></h2>
<p><span style="font-weight: 400;">Among the types of Information that netwrk collects, by itself or through third parties, there are: geographic position, email address, first and last name, and your phone number. Other Personal Data collected may be described in other sections of this privacy policy or by dedicated explanation text contextually when we gather it. The information may be freely provided by you, or collected automatically when using netwrk.</span></p>
<p><span style="font-weight: 400;">Any use of Cookies - or of other tracking tools - by this Application or by the owners of third party services used by this Application, unless stated otherwise, serves to identify you and remember their preferences, for the sole purpose of providing the service required.</span></p>
<p><span style="font-weight: 400;">Failure to provide certain Personal Data may make it impossible for netwrk to provide its services.</span></p>
<p><span style="font-weight: 400;">You are responsible for any information of third parties obtained, published or shared through netwrk and confirm the third party's consent to provide the information to netwrk.</span></p>
<p>&nbsp;</p>
<h3><strong>Methods of processing</strong></h3>
<p><span style="font-weight: 400;">Things get a little technical here (welcome to the world of technology!).</span></p>
<p><span style="font-weight: 400;">The Data Controller processes the Data of Users in a proper manner and shall take appropriate security measures to prevent unauthorized access, disclosure, modification, or unauthorized destruction of the Data.</span></p>
<p><span style="font-weight: 400;">The Data processing is carried out using computers and/or IT enabled tools, following organizational procedures and modes strictly related to the purposes indicated. In addition to the Data Controller, in some cases, the Data may be accessible to certain types of persons in charge, involved with the operation of the site (administration, sales, marketing, legal, system administration) or external parties (such as third party technical service providers, mail carriers, hosting providers, IT companies, communications agencies) appointed, if necessary, as Data Processors by the Owner. The updated list of these parties may be requested from the Data Controller at any time.</span></p>
<h3><strong>Place</strong></h3>
<p><span style="font-weight: 400;">The Data is processed at the Data Controller's operating offices and in any other places where the parties involved with the processing are located. For further information, please contact us.</span></p>
<h3><strong>Retention time</strong></h3>
<p><span style="font-weight: 400;">The Data is kept for the time necessary to provide the service requested, or stated by the purposes outlined in this document, and the you can always request that the Data Controller suspend or remove the data.</span></p>
<p>&nbsp;</p>
<h2><strong>The use of the collected Data</strong></h2>
<p><span style="font-weight: 400;">The information collected from you allows us to provide the best services and product possible. Specifically, but not limited to, the following purposes: Access to third party accounts, Location-based interactions and Contacting you through e-mail or phone.</span></p>
<p><span style="font-weight: 400;">The Personal Data used for each purpose is outlined in the following specific sections.</span></p>
<p>&nbsp;</p>
<h2><strong>Facebook and other social media permissions asked by this Application</strong></h2>
<p><span style="font-weight: 400;">This Application may ask for some Facebook permissions allowing it to perform actions with the User's Facebook account and to retrieve information, including Personal Data, from it. Other social media like Twitter, snapchat, or linkedin can have the same or similar permissions.</span></p>
<p><span style="font-weight: 400;">For more information about the following permissions, refer to the </span><a href="https://developers.facebook.com/docs/authentication/permissions/"><span style="font-weight: 400;">Facebook permissions documentation</span></a><span style="font-weight: 400;"> and to the </span><a href="https://www.facebook.com/about/privacy/"><span style="font-weight: 400;">Facebook privacy policy</span></a><span style="font-weight: 400;">, along with any other social permissions documentation or privacy policies.</span></p>
<p><span style="font-weight: 400;">The permissions asked are the following:</span></p>
<h3><strong>Basic information</strong></h3>
<p><span style="font-weight: 400;">By default, this includes certain your information such as id, name, picture, gender, and locale. Certain connections, such as the Friends, are also available. If you have made more information public, it will be available.</span></p>
<h3><strong>Access Friend Lists</strong></h3>
<p><span style="font-weight: 400;">Provides access to any friend lists you have created.</span></p>
<h3><strong>Interests</strong></h3>
<p><span style="font-weight: 400;">Provides access to your list of interests.</span></p>
<h3><strong>News Feed and Wall</strong></h3>
<p><span style="font-weight: 400;">Provides access to all the posts in the your news feed and enables netwrk to perform searches against it.</span></p>
<h3><strong>Publish App Activity</strong></h3>
<p><span style="font-weight: 400;">Allows the app to publish to the Open Graph using Built-in Actions, Achievements, Scores, or Custom Actions. The app can also publish other activity which is detailed in the Facebook's Publishing Permissions document.</span></p>
<h3><strong>Publish to the Wall</strong></h3>
<p><span style="font-weight: 400;">Enables the app to post content, comments, and likes to your stream and to the streams of your friends.</span></p>
<h2><strong>Detailed information on the processing of Personal Data</strong></h2>
<p><span style="font-weight: 400;">Personal Data is collected for the following purposes and using the following services:</span></p>
<ul>
<li style="font-weight: 400;">
<h3><strong>Access to third party accounts</strong></h3>
</li>
<li style="font-weight: 400;">
<h3><strong>Contacting the User</strong></h3>
</li>
<li style="font-weight: 400;">
<h3><strong>Location-based interactions</strong></h3>
</li>
</ul>
<h2><strong>Additional information about Data collection and processing</strong></h2>
<h2><strong>Third-Party Content and Integrations</strong></h2>
<h3><span style="font-weight: 400;">The services may also contain third-party links and search results, include third-party integrations, or offer a co-branded or third-party-branded service. Through these links, third-party integrations, and co-branded or third-party-branded services, you may be providing information (including personal information) directly to the third party, us, or both. You acknowledge and agree that we are not responsible for how those third parties collect or use your information. As always, we encourage you to review the privacy policies of every third-party website or service that you visit or use, including those third parties you interact with through our services.</span></h3>
<p><br /><br /><br /></p>
<h3><strong>Legal action</strong></h3>
<p><span style="font-weight: 400;">The User's Personal Data may be used for legal purposes by netwrk, in Court or in the stages leading to possible legal action arising from improper use of this Application or the related services.</span></p>
<p><span style="font-weight: 400;">The User declares to be aware that netwrk may be required to reveal personal data upon request of public authorities.</span></p>
<h3><strong>Additional information about User's Personal Data</strong></h3>
<p><span style="font-weight: 400;">In addition to the information contained in this privacy policy, this Application may provide the User with additional and contextual information concerning particular services or the collection and processing of Personal Data upon request.</span></p>
<h3><strong>System logs and maintenance</strong></h3>
<p><span style="font-weight: 400;">For operation and maintenance purposes, this Application and any third party services may collect files that record interaction with this Application (System logs) or use for this purpose other Personal Data (such as IP Address).</span></p>
<h3><strong>Information not contained in this policy</strong></h3>
<p><span style="font-weight: 400;">More details concerning the collection or processing of information may be requested from netwrk at any time. Please see the contact information at the beginning of this document.</span></p>
<h3><strong>The rights of Users</strong></h3>
<p><span style="font-weight: 400;">You have the right, at any time, to know whether your information has been stored and can consult the netwrk to learn about their contents and origin, to verify their accuracy or to ask for them to be supplemented, cancelled, updated or corrected, or for their transformation into anonymous format or to block any data held in violation of the law, as well as to oppose their treatment for any and all legitimate reasons. Requests should be sent to us. To determine whether this application or any of the third party services it uses honor the &ldquo;Do Not Track&rdquo; requests, please read their privacy policies or contact us.</span></p>
<h3><strong>Changes to this privacy policy</strong></h3>
<p><span style="font-weight: 400;">Netwrk reserves the right to make changes to this privacy policy at any time by giving notice to its people on this page. It is strongly recommended to check this page often, referring to the date of the last modification listed at the bottom. If someone objects to any of the changes to the Policy, theyr must cease using netwrk and can request that we remove their ifo. Unless stated otherwise, the then-current privacy policy applies to all information we have about our people.</span></p>
<h3><strong>Information about this privacy policy</strong></h3>
<p><span style="font-weight: 400;">Netwrk is responsible for this privacy policy. Any questions, feel free to contact us.</span></p>
</div>

app/views/home/terms_of_use.html.erb
<div class="container policy">
  <h2>
  	Web Site Terms and Conditions of Use
  </h2>

  <h3>
  	1. Terms
  </h3>

  <p>
  	By accessing this web site, you are agreeing to be bound by these
  	web site Terms and Conditions of Use, all applicable laws and regulations,
  	and agree that you are responsible for compliance with any applicable local
  	laws. If you do not agree with any of these terms, you are prohibited from
  	using or accessing this site. The materials contained in this web site are
  	protected by applicable copyright and trade mark law.
  </p>

  <h3>
  	2. Use License
  </h3>

  <ol type="a">
  	<li>
  		Permission is granted to temporarily download one copy of the materials
  		(information or software) on Netwrk's web site for personal,
  		non-commercial transitory viewing only. This is the grant of a license,
  		not a transfer of title, and under this license you may not:

  		<ol type="i">
  			<li>modify or copy the materials;</li>
  			<li>use the materials for any commercial purpose, or for any public display (commercial or non-commercial);</li>
  			<li>attempt to decompile or reverse engineer any software contained on Netwrk's web site;</li>
  			<li>remove any copyright or other proprietary notations from the materials; or</li>
  			<li>transfer the materials to another person or "mirror" the materials on any other server.</li>
  		</ol>
  	</li>
  	<li>
  		This license shall automatically terminate if you violate any of these restrictions and may be terminated by Netwrk at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.
  	</li>
  </ol>

  <h3>
  	3. Disclaimer
  </h3>

  <ol type="a">
  	<li>
  		The materials on Netwrk's web site are provided "as is". Netwrk makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, Netwrk does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.
  	</li>
  </ol>

  <h3>
  	4. Limitations
  </h3>

  <p>
  	In no event shall Netwrk or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on Netwrk's Internet site, even if Netwrk or a Netwrk authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
  </p>

  <h3>
  	5. Revisions and Errata
  </h3>

  <p>
  	The materials appearing on Netwrk's web site could include technical, typographical, or photographic errors. Netwrk does not warrant that any of the materials on its web site are accurate, complete, or current. Netwrk may make changes to the materials contained on its web site at any time without notice. Netwrk does not, however, make any commitment to update the materials.
  </p>

  <h3>
  	6. Links
  </h3>

  <p>
  	Netwrk has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Netwrk of the site. Use of any such linked web site is at the user's own risk.
  </p>

  <h3>
  	7. Site Terms of Use Modifications
  </h3>

  <p>
  	Netwrk may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.
  </p>

  <h3>
  	8. Governing Law
  </h3>

  <p>
  	Any claim relating to Netwrk's web site shall be governed by the laws of the State of Indiana without regard to its conflict of law provisions.
  </p>

  <p>
  	General Terms and Conditions applicable to Use of a Web Site.
  </p>

  <h3>
    9. Age rating
  </h3>

  <p>
    Netwrk is rated 17 and up.
  </p>
</div>